### ISSUE TITLE
unable to login with no clear error message.

### ISSUE THREAD

**Issue by kevinhuy** [codeaffen/pyhpipam#38]
Hello,

I m trying to test phpypam with the sample provide. 

pi = phpypam.api(
  url='http://myipam.com',
  app_id='xx',
  token='xxxxx',
  username='xxx',
  password='xxx',
  ssl_verify=False
)
pi.get_entity(controller='sections')

And i got the following error 

Traceback (most recent call last):
  File "test_ipam.py", line 10, in <module>
    ssl_verify=False
  File "/lib/python3.6/site-packages/phpypam/core/api.py", line 66, in __init__
    self._login()
  File "/lib/python3.6/site-packages/phpypam/core/api.py", line 131, in _login
    resp = self._query(method=POST, auth=_auth)
  File "/lib/python3.6/site-packages/phpypam/core/api.py", line 121, in _query
    raise PHPyPAMException(code=result['code'], message=result['message'])
phpypam.core.exceptions.PHPyPAMException

**Versions:**

- python 3.6.0
- phpypam

**Comment by cmeissner** [comment]
Thank you @kevinhuy for reporting this bug. I try to understand and reproduce the error. So I have some questions:

1. which version of phpypam did you use for your tests?
2. did you really try to connect to a unsecure 'http' end point?

Best regards

Christian

**Comment by kevinhuy** [comment]
Hi Christian,

1. my using phpypam==1.0.0
2. i can use both , but in my ipam setting url is specify with http.

**Comment by cmeissner** [comment]
Ok, the root cause is the unencrypted api endpoint. PhpIPAM does not support 'user token' without SSL nor encryption by default. If you don't have set `$api_allow_unsafe` to `true` in your config.php you can't connect via `http` to phpIPAM.

```
$ curl -X POST --user username:password http://ipam.example.com/api/app_id/user/ -i
HTTP/1.1 503 Service Unavailable
Date: Mon, 04 Jan 2021 00:08:26 GMT
Server: Apache/2.4.37 (centos) OpenSSL/1.1.1g
X-Powered-By: PHP/7.2.24
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-cache
Pragma: no-cache
Vary: Accept-Encoding
Set-Cookie: phpipam=7e06m16vdrdqi73mbqt2teu0mi; expires=Tue, 05-Jan-2021 00:08:26 GMT; Max-Age=86400; path=/; HttpOnly
Connection: close
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

{"code":503,"success":false,"message":"SSL connection is required for API","time":0}
```

The bug is that we don't catch the exception correctly. We will fix this asap. 

If you set `$api_allow_unsafe` to `true` you can use our library too. **But be aware this is not recommended because of security risk.**

**Comment by kevinhuy** [comment]
@cmeissner thanks for your feedback , i will wait on your fix then.

**Comment by cmeissner** [comment]
@kevinhuy finally I pushed the changes that are needed for that bug. It would be great if you can test it and gave us feedback in form of a review.

**Comment by kevinhuy** [comment]
@cmeissner   did you push the change on pip or i need to clone the repo ?

**Comment by cmeissner** [comment]
I only pushed it to develop here. After getting required reviews a new version will be created and published on you.

**Comment by kevinhuy** [comment]
ok i just test it works, i m able to pull the info .  :)
